[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/index-db.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index-db.html"
  status = 200

# Function configuration
[functions]
  node_bundler = "esbuild"
